import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/app/globals.css";
import SessionProvider from "@/components/providers/SessionProvider";
import Navbar from "../components/Layout/NavBar";
import Footer from "../components/Layout/Footer";

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const isAdmin =
    typeof window !== "undefined"
      ? window.location.pathname.startsWith("/admin")
      : false;

  return (
    <html lang="en">
      <body className={`${montserrat.variable} antialiased`}>
        <SessionProvider>
          {!isAdmin && <Navbar />}
          <div>{children}</div>
          {!isAdmin && <Footer />}
        </SessionProvider>
      </body>
    </html>
  );
}
