import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import SessionProvider from "@/components/providers/SessionProvider";
import Navbar from "../components/Layout/NavBar";
import Footer from "../components/Layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
   
  const isAdmin = typeof window !== "undefined" ? window.location.pathname.startsWith("/admin") : false;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          {!isAdmin && <Navbar />}
          <div className="">
            {children}
          </div>
          {!isAdmin && <Footer />}
        </SessionProvider>
      </body>
    </html>
  );
}
